### PR TITLE
Fix generate identity hang and add more metrics

### LINKED ISSUE #659: Xdbg generate identity hangs
```
$ cargo xdbg -d generate --entity identity --amount 10
    Finished `release` profile [optimized] target(s) in 0.27s
     Running `target/release/xdbg -d generate --entity identity --amount 10`
██████████░░░░░░░░░░ 5/10 elapsed 0s remaining 00:00:00       
```

```
2025-03-21T14:04:08.688-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.691-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.693-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.694-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.696-0400    INFO    replication     publishing to originator        {"originator_id": 100}
2025-03-21T14:04:08.696-0400    INFO    replication     connecting to node      {"nodeID": 100}
2025-03-21T14:04:08.696-0400    INFO    replication     publishing to originator        {"originator_id": 100}
2025-03-21T14:04:08.697-0400    INFO    replication     publishing to originator        {"originator_id": 100}
2025-03-21T14:04:08.698-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.698-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.698-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.700-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.700-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.701-0400    INFO    replication     got inbox ids   {"method": "GetInboxIds", "numResponses": 1}
2025-03-21T14:04:08.702-0400    INFO    replication     publishing to originator        {"originator_id": 100}
2025-03-21T14:04:08.703-0400    INFO    replication     publishing to originator        {"originator_id": 100}
2025-03-21T14:04:08.703-0400    INFO    replication     publishing to originator        {"originator_id": 200}
2025-03-21T14:04:08.703-0400    INFO    replication     connecting to node      {"nodeID": 200}
2025-03-21T14:04:08.704-0400    INFO    replication     publishing to originator        {"originator_id": 100}
2025-03-21T14:04:08.705-0400    INFO    replication     publishing to originator        {"originator_id": 200}
2025-03-21T14:04:08.706-0400    INFO    replication     publishing to originator        {"originator_id": 100}
2025-03-21T14:04:08.706-0400    INFO    replication     publishing to originator        {"originator_id": 100}
2025-03-21T14:04:08.725-0400    ERROR   replication     error publishing to node. Retrying with the next one    {"failed_node": 200, "error": "rpc error: code = Internal desc = error publishing payer envelopes: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:5051: connect: connection refused\""}
2025-03-21T14:04:08.725-0400    ERROR   replication     error publishing to node. Retrying with the next one    {"failed_node": 200, "error": "rpc error: code = Internal desc = error publishing payer envelopes: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:5051: connect: connection refused\""}
2025-03-21T14:04:08.762-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1643, "wait_time": 20}
2025-03-21T14:04:08.763-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1644, "wait_time": 20}
2025-03-21T14:04:08.763-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1645, "wait_time": 20}
2025-03-21T14:04:08.764-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/5e9341727c33eb131ba532077f3df684974f0311114817908b0c7f5b3580c8ec"}
2025-03-21T14:04:08.764-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/84a893746b434c0ad9ab99dbd819049fb8157c188a87cbccaaec2c8e15cb63f3"}
2025-03-21T14:04:08.764-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/ce4126623ff6d756e3e86b3a3b0f372d8ca02cb579c46fff067da05b5ed83e1b"}
2025-03-21T14:04:08.765-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1646}
2025-03-21T14:04:08.766-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1647}
2025-03-21T14:04:08.766-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1648}
2025-03-21T14:04:08.774-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1646, "wait_time": 30}
2025-03-21T14:04:08.775-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1647, "wait_time": 30}
2025-03-21T14:04:08.775-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/564f1db0a1a597680dd3aaac25d2b19df2d53b2f771cb09f6cb4ffc86f20daf9"}
2025-03-21T14:04:08.776-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1648, "wait_time": 30}
2025-03-21T14:04:08.776-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/9781832aa39405748d6159ad28d054cb136dbf27dae8df9cc554155361fff799"}
2025-03-21T14:04:08.777-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/783cf30ce6673c204307b92b3c3b96ab61b2e7fc9f61a8f7506ec1337ae07fc9"}
2025-03-21T14:04:08.777-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1649}
2025-03-21T14:04:08.777-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1650}
2025-03-21T14:04:08.778-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1651}
2025-03-21T14:04:08.785-0400    ERROR   replication     Chosen node for cursor check is unreachable     {"targetNodeId": 200}
2025-03-21T14:04:08.786-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1649, "wait_time": 40}
2025-03-21T14:04:08.786-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/6927c73657a650b51d3430d0d4846baad58b942a8f551912e3d4ba788c4977b6"}
2025-03-21T14:04:08.787-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1652}
2025-03-21T14:04:08.796-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1650, "wait_time": 50}
2025-03-21T14:04:08.797-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1651, "wait_time": 50}
2025-03-21T14:04:08.797-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/6c5100b70a8739e2f7a2a680a5dc137c06f736834d8fea6b2e89a7196d023384"}
2025-03-21T14:04:08.797-0400    DEBUG   replication     Finished waiting for publisher  {"envelope_id": 1652, "wait_time": 50}
2025-03-21T14:04:08.798-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/d01cea204a9e12cc9c2ab959628c4966b9a1a5ef816f474ed1fa69bce47c4d3a"}
2025-03-21T14:04:08.798-0400    INFO    replication     publishing to blockchain        {"topic": "identity_updates_v1/dadf439d82561097014b53f50e097aa1c9d8293055134ed6373dd50eb393be41"}
2025-03-21T14:04:08.799-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1653}
2025-03-21T14:04:08.799-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1654}
2025-03-21T14:04:08.799-0400    DEBUG   replication.SQLBackedNonceManager       Generated Nonce {"nonce": 1655}
2025-03-21T14:04:08.805-0400    ERROR   replication     Chosen node for cursor check is unreachable     {"targetNodeId": 200}
2025-03-21T14:04:08.835-0400    DEBUG   replication.subscribeWorker     Received new batch      {"numEnvelopes": 10}
2025-03-21T14:04:08.938-0400    DEBUG   replication.subscribeWorker     Received new batch      {"numEnvelopes": 2}
2025-03-21T14:04:09.042-0400    ERROR   replication     Chosen node for cursor check is unreachable     {"targetNodeId": 200}
2025-03-21T14:04:09.043-0400    ERROR   replication     Chosen node for cursor check is unreachable     {"targetNodeId": 200}
2025-03-21T14:04:09.045-0400    ERROR   replication     Chosen node for cursor check is unreachable     {"targetNodeId": 200}
2025-03-21T14:04:09.568-0400    DEBUG   replication.SQLBackedNonceManager       Replenished nonces...   {"starting_nonce": 1656, "num_nonces": 10}
2025-03-21T14:04:23.916-0400    DEBUG   replication     stream closed
2025-03-21T14:04:23.916-0400    DEBUG   replication     stream closed
2025-03-21T14:04:23.916-0400    DEBUG   replication     stream closed
2025-03-21T14:04:23.916-0400    DEBUG   replication     stream closed
2025-03-21T14:04:23.916-0400    DEBUG   replication     stream closed
```

### PR DESCRIPTION
**Pull request by mkysel**
In a rare case when there are no logs in a batch of 1000, the batch start point never moves and the entire indexer hangs. Fix it.

Also add metrics that were used to debug this.

Fixes #659 

## Summary by CodeRabbit

- **New Features**
  - Enhanced connection monitoring with a new interceptor for managing open connections in the API server.
  - Refined logging across key operations, including block handling and identity updates, with precise timestamp details.
  - Integrated Prometheus-based metrics to track active API connections for improved performance insights.

- **Bug Fixes**
  - Corrected the logic for updating the `fromBlock` variable to ensure it reflects the latest available block.

- **Documentation**
  - Added detailed logging statements to improve observability of operations.

### CODE REVIEW

File: pkg/blockchain/rpcLogStreamer.go [hunk 1]
```diff
@@ -168,6 +168,10 @@ func (r *RpcLogStreamer) watchContract(watcher ContractConfig) {
 			// reset self-termination timer
 			timer.Reset(watcher.maxDisconnectTime)
 
+			if nextBlock != nil {
+				fromBlock = *nextBlock
+			}
```
Comment (mkysel) [inline pkg/blockchain/rpcLogStreamer.go:173]: the actual cause of the bug
